FROM fedora:27
# install dependencies
RUN dnf install -y \
	boost-devel \
	clang \
	cmake \
	cryptopp-devel \
	gcc-c++ \
	gdb \
	git \
	gnutls-devel \
	hwloc \
	hwloc-devel \
	libaio-devel \
	libasan \
	libpciaccess-devel \
	libubsan \
	libxml2-devel \
	lksctp-tools-devel \
	lz4-devel \
	make \
	meson \
	meson \
	ninja-build \
	numactl-devel \
	protobuf-compiler \
	protobuf-devel \
	python3 \
	ragel \
	systemtap-sdt-devel \
	xfsprogs-devel \
	yaml-cpp-devel \
	zlib-devel \

